# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'templevilleApp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for templevilleApp
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]
    pod 'RNFS', :path => '../node_modules/react-native-fs'
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
